export const GET_COVID_DATA_FOR_SELECTED_COUNTRY = 'GET_COVID_DATA_FOR_SELECTED_COUNTRY'
export const GET_COVID_DATA = 'GET_COVID_DATA'
export const SET_COVID_DATA_FOR_SELECTED_COUNTRY = 'SET_COVID_DATA_FOR_SELECTED_COUNTRY'
